### ISSUE TITLE
Стать page action

### ISSUE THREAD

**Issue by isqua** [isqua/asocial#17]
https://developer.chrome.com/extensions/pageAction

**Comment by fyvfyv** [comment]
Чтобы стать pageAction - нужно описывать логику, когда подсвечивать иконку самостоятельно, а не просто прописать в манифесте. То я думаю логично заасайнить этот ишью на тебя.

**Comment by isqua** [comment]
Йесть два варианта:
- подсвечивать иконку когда сайт заблочен (но и так понятно, что он заблочен, без иконки);
- подсвечивать иконку, когда у юзера открыт сайт, который можно заблочить.

И я даже не знаю, может оба не нужны?

**Comment by fyvfyv** [comment]
В чем профит этих подсвечиваний?

**Comment by isqua** [comment]
Не нужно.
