### ISSUE TITLE
На странице настроек подсвечивать текущие правила

### ISSUE THREAD

**Issue by isqua** [isqua/asocial#39]
Нужен какой-то маркер, чтобы отличать то, что щас блочит что-нибудь.

**Comment by isqua** [comment]
Например точечкой помечать!

**Comment by fyvfyv** [comment]
Какой еще точечкой?

**Comment by isqua** [comment]
Например такими:

<img width="459" alt="asocial_options" src="https://cloud.githubusercontent.com/assets/529247/18493037/2ae8f1e0-7a17-11e6-9d8e-2c7d03ad97c2.png">

Боюсь отмечать цветом, потому что с ховером и редактируемым правилом очень полосато будет. А ты как думаешь отмечать их?

**Comment by fyvfyv** [comment]
Мне нравится точечка. Можно еще шрифтик жирненький сделать.
