### ISSUE TITLE
Спроектировать страницу настроек

### ISSUE THREAD

**Issue by isqua** [isqua/asocial#5]
**Дизайн-задача!** Хочу настраивать вот что:
1. Таймер. Знаю, что щас буду работать два часа, и в эти два часа мне не надо отвлекаться. Взвожу таймер, два часа ничего не открывается.
2. Расписание. Работаю например с 10 до 19 каждый день, и хочу поставить, что с пн по пт с 10 до 19 у меня выключены фейсбук, вк, твиттер и, ну, реддит. Или хочу например по средам и четвергам с 12 до 14 и с 15 до 17 не отвлекаться на фейсбук, а с 11 до 13.30 и с 16.15 до 21.03 не отвлекаться на вк.

Можешь накидать вёрстку на кодпене, или нарисовать картинку в фотошопе или скетче, что тебе удобнее. Нужно придумать интерфейс, короче.

**Comment by fyvfyv** [comment]
[Набросал в кодепене.](http://codepen.io/fyvfyv/pen/bebxeb)
С таймером все просто, указываем значения и жмем запуск.
С расписанием сделал 2 варианта:
1) В виде календаря. Выделили область/ткнули куда-нибудь - появился попап, уточнили время, соцсети и записали.
2) В виде набора правил, как у файрволла. Добавляем правила, которые потом собираются в график нужный.

**Comment by isqua** [comment]
Ой всё. Селект с минутами, Карл! На тебе [попроще](http://codepen.io/isqua/pen/qZeYXJ).

UPD: Теперь там есть выбор времени и сетей.

**Comment by fyvfyv** [comment]
Ну или так=) Верстать все это дело?

**Comment by isqua** [comment]
Зафиксирую картинкой с подписями:

<img width="903" alt="a_pen_by_isqua" src="https://cloud.githubusercontent.com/assets/529247/15580238/8fa96fea-2370-11e6-8a2b-1950e602054a.png">

font-family предлагаю просто `sans-serif`, чтобы брался тот, который пользователь себе настроил. Цвета и отступы можешь менять на своё усмотрение, обсудим.
