### ISSUE TITLE
Не сохраняет временны интервалы

### ISSUE THREAD

**Issue by rezunenko** [isqua/asocial#66]
При вводе любого диапазона времен получается "весь день". 
Соответственно при любом ограничении весь день лента будет и недоступна.

**Comment by fyvfyv** [comment]
@rezunenko А в каком формате вводили время?

**Comment by rezunenko** [comment]
в настоящий момент данная проблема не актуальна, так как не воспроизводится. Проблема трансформировалась в другое issue https://github.com/isqua/asocial/issues/67
